apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 4
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: renatogroffe/apitemperaturas-dotnet7-minimal:1